### ISSUE TITLE
Hi, I'm not able to sign in to the software using username- test@example.com, password- password 

### ISSUE THREAD

**Issue by BaizaSajjad** [a1telekom/ra-risk-coverage#5]
Hi, I'm not able to sign in to the software using username- test@example.com, password- password

**Comment by krokce** [comment]
- check if you successfully loaded the selected data model (step 7 from README), i.e. confirm that **amx** database exists in your MySQL DB and  table **amx_user** is populated with at least 1 record for user **test@example.com**.

- see step 10 from the README for hint how to create new user

- check if you see any error messages in the log / terminal and post them here

**Comment by BaizaSajjad** [comment]
Thanks for your response.
After loading data model in step 7, the following is the output I'm getting. Does this mean RAG data model was successfully loaded?
And how can I load the amx database?

C:\Users\Baiza.Sajjad\ra-risk-coverage>mysql -u rrc_user -p -h localhost < server/db/rrc_rag.sql
Enter password: ************
C:\Users\Baiza.Sajjad\ra-risk-coverage>

**Comment by BaizaSajjad** [comment]
The following is the output of show databases:

 mysql> SHOW databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| tag                |
+--------------------+
2 rows in set (0.03 sec)

**Comment by krokce** [comment]
Sorry, my bad - database name is **tag**.
 
You can check if RAG data model was successfully loaded by checking the content of the **tag** database. If there are tables inside - you should be set to go.  Also, you can check the contents of table **tag.cvg_risk** (e.g. `SELECT * FROM tag.cvg_risk;`). There should be all Risks from the RAG model.

If there are no tables - you should check if the path to `rrc_rag.sql` file that you used in your `mysql` command is right. The **README** is written with Linux in mind, so I guess in Windows you may need to change the command to be something like: `mysql -u rrc_user -p -h localhost < C:\Users\Baiza.Sajjad\ra-risk-coverage\server\db\rrc_rag.sql`

Hope this helps...

**Comment by BaizaSajjad** [comment]
Thanks for your help.
I can see tables in tag database. Also, I can see Risks from the RAG model in the table tag.cvg_risk.

There is a username 'test' in amx_user table. Also, I could create new users in amx_user table. Still on the software, I'm not able to sign in.

The error I'm getting is:
Incorrect password! Count: (1). Please try again or contact your RA Risk Coverage tool admin. 

Please find the logs below:

mysql> select * from amx_user;
+----------+------------------+------------------------------------------------------------------+---------+--------------+---------------+--------------+---------------------+----------+---------------------+
| USERNAME | EMAIL            | PASSWORD                                                         | OPCO_ID | ACCESS_LEVEL | LOGIN_SUCCESS | LOGIN_FAILED | CREATED             | MODIFIED | LAST_LOGIN_ATTEMPT  |
+----------+------------------+------------------------------------------------------------------+---------+--------------+---------------+--------------+---------------------+----------+---------------------+
| test     | test@example.com | 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8 |      36 |          100 |             5 |            0 | 2017-01-03 15:35:14 | NULL     | 2018-04-17 09:12:12 |
+----------+------------------+------------------------------------------------------------------+---------+--------------+---------------+--------------+---------------------+----------+---------------------+
1 row in set (0.00 sec)


mysql> use tag;
Database changed
mysql> select * from amx_user;
+----------+-------------------+------------------------------------------------------------------+---------+--------------+---------------+--------------+---------------------+----------+---------------------+
| USERNAME | EMAIL             | PASSWORD                                                         | OPCO_ID | ACCESS_LEVEL | LOGIN_SUCCESS | LOGIN_FAILED | CREATED             | MODIFIED | LAST_LOGIN_ATTEMPT  |
+----------+-------------------+------------------------------------------------------------------+---------+--------------+---------------+--------------+---------------------+----------+---------------------+
| Baiza    | Baiza@example.com | 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8 |      36 |          100 |             0 |            0 | 2020-04-20 15:24:29 | NULL     | NULL                |
| test     | test@example.com  | 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8 |      36 |          100 |             5 |            0 | 2017-01-03 15:35:14 | NULL     | 2018-04-17 09:12:12 |
+----------+-------------------+------------------------------------------------------------------+---------+--------------+---------------+--------------+---------------------+----------+---------------------+
2 rows in set (0.00 sec)

mysql> INSERT INTO amx_user (
    -> USERNAME,
    -> EMAIL,
    -> PASSWORD,
    -> OPCO_ID)
    -> VALUES(
    -> 'Jen',
    -> 'Jen@example.com',
    -> SHA2('password',256),
    -> 36);
Query OK, 1 row affected (0.02 sec)

**Comment by krokce** [comment]
This looks good.

You should be able to log in using:
- user: `Baiza@example.com` or `Jen@example.com` or the default `test@example.com`
- password: `password`

If you still can't log-in you may want to check if you created the `db.js` file under step **6** of the setup guide from the README, and if the content is correct according to your DB setup (DB *user*, *password*, *host*, etc.)

**Please note** that in your case the file location should be `C:\Users\Baiza.Sajjad\ra-risk-coverage\server\utils\db.js`

**Comment by BaizaSajjad** [comment]
Hi. I rechecked and I have already created db.js in - C:\Users\Baiza.Sajjad\ra-risk-coverage\server\utils:

var mysql = require('mysql');
var pool = mysql.createPool({
	connectionLimit	: 10,
	host : 'localhost',
	database : 'tag',
	user : 'rrc_user',
	password : 'rrc_password'
});
module.exports = pool;


logs:
C:\Users\Baiza.Sajjad\ra-risk-coverage\server\utils>node db.js

C:\Users\Baiza.Sajjad\ra-risk-coverage\server\utils>

Still not able to sign in :(

**Comment by krokce** [comment]
Did you created the Database user `rrc_user` in your MySQL instance and gave the necessary grants as described in step **5**? 

Could you post the errors you get in the console logs when you run the application and try to log-in (i.e. after you run `grunt serve`) ?

**Comment by BaizaSajjad** [comment]
Yes I did:
C:\Users\Baiza.Sajjad\ra-risk-coverage>mysql -u root -p -h localhost
Enter password: *********
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 98
Server version: 8.0.19 MySQL Community Server - GPL

Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> GRANT ALL PRIVILEGES ON tag.* TO 'rrc_user';
Query OK, 0 rows affected (0.03 sec)


After running grunt serve, it opens the default browser. logs:

Running "wait" task
>> Waiting for server reload...
Done waiting!

Running "open:server" (open) task

Running "watch" task
Waiting...
GET /api/config 304 14.659 ms - -
Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Handshake.Sequence._packetToError (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Handshake.ErrorPacket (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\protocol\sequences\Handshake.js:123:18)
    at Protocol._parsePacket (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Protocol._enqueue (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\Pool.js:202:8)
    at getApiEndpoint (C:/Users/Baiza.Sajjad/ra-risk-coverage/server/api/lookup/lookup.controller.js:184:8)
    at Layer.handle [as handle_request] (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\express\lib\router\layer.js:95:5) {
  code: 'ER_NOT_SUPPORTED_AUTH_MODE',
  errno: 1251,
  sqlMessage: 'Client does not support authentication protocol requested by server; consider upgrading MySQL client',
  sqlState: '08004',
  fatal: true
}
Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Handshake.Sequence._packetToError (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Handshake.ErrorPacket (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\protocol\sequences\Handshake.js:123:18)
    at Protocol._parsePacket (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Protocol._enqueue (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\Pool.js:202:8)
    at getApiEndpoint (C:/Users/Baiza.Sajjad/ra-risk-coverage/server/api/lookup/lookup.controller.js:184:8)
    at Layer.handle [as handle_request] (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\express\lib\router\layer.js:95:5)
Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Handshake.Sequence._packetToError (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Handshake.ErrorPacket (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\protocol\sequences\Handshake.js:123:18)
    at Protocol._parsePacket (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Protocol._enqueue (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\Pool.js:202:8)
    at getApiEndpoint (C:/Users/Baiza.Sajjad/ra-risk-coverage/server/api/lookup/lookup.controller.js:129:8)
    at Layer.handle [as handle_request] (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\express\lib\router\layer.js:95:5) {
  code: 'ER_NOT_SUPPORTED_AUTH_MODE',
  errno: 1251,
  sqlMessage: 'Client does not support authentication protocol requested by server; consider upgrading MySQL client',
  sqlState: '08004',
  fatal: true
}
Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Handshake.Sequence._packetToError (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Handshake.ErrorPacket (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\protocol\sequences\Handshake.js:123:18)
    at Protocol._parsePacket (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Protocol._enqueue (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\mysql\lib\Pool.js:202:8)
    at getApiEndpoint (C:/Users/Baiza.Sajjad/ra-risk-coverage/server/api/lookup/lookup.controller.js:129:8)
    at Layer.handle [as handle_request] (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\Baiza.Sajjad\ra-risk-coverage\node_modules\express\lib\router\layer.js:95:5)
GET /api/lookups/getSystems 500 246.409 ms - -
GET /api/lookups/getOpcos 500 310.428 ms - -

**Comment by krokce** [comment]
It seems you are running MySQL server version > 8, which by default uses other authentication method which is not supported by this node library. You should be able to fix this by changing the default authentication method for the **rrc_user** to *mysql_native_password*. Run the following commands from *mysql console* (logged as `root`):

1. `ALTER USER 'rrc_user' IDENTIFIED WITH mysql_native_password BY 'rrc_password';`
2. `flush privileges;`

**Comment by BaizaSajjad** [comment]
Thanks for your help. This could solve the issue.
